<a href="https://colab.research.google.com/github/SnapeSnoop/MachineLearning/blob/main/MCLPT5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

Saving spam.csv to spam.csv


In [82]:
df = pd.read_csv('spam.csv', encoding='latin-1') # spesifiksi encoding diperlukan karena data tidak menggunakan UTF-8

df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [83]:
df = df.drop(df.iloc[:,2:], axis=1)

df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
# Data untuk rename kolom v1 dan v2
new_cols = {
    'v1': 'Labels',
    'v2': 'SMS'
}

# Rename nama kolom v1 dan v2
df = df.rename(columns=new_cols)

# cek data
df.head()

In [ ]:
# Cek Jumlah Data Per Kelas
print(df['Labels'].value_counts())
print('\n')

# Cek Kelengkapan Data
print(df.info())
print('\n')

# Cek Statistik Deskriptif
print(df.describe())

In [85]:
# Data untuk label
new_labels = {
    'spam': 1,
    'ham': 0
}

# Encode label
df['Labels'] = df['Labels'].map(new_labels)

# Cek data
df.head()

Labels                                                SMS
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [86]:
X = df['SMS'].values
y = df['Labels'].values

Soal No 1 

In [107]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords

# Split data training dan testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=50)

# Inisiasi CountVectorizer
cv = CountVectorizer(stop_words = (["I", "think","goes","to"]))

# Fitting dan transform X_train dengan CountVectorizer
X_train = cv.fit_transform(X_train)

# Transform X_test
# Mengapa hanya transform? Alasan yang sama dengan kasus pada percobaan ke-3
# Kita tidak menginginkan model mengetahui paramter yang digunakan oleh CountVectorizer untuk fitting data X_train
# Sehingga, data testing dapat tetap menjadi data yang asing bagi model nantinya
X_test = cv.transform(X_test)


X_train.shape


(4457, 7724)

In [108]:
cv.stop_words


['I', 'think', 'goes', 'to']

Soal 2

In [90]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
 
docs=["the house had a tiny little mouse",
      "the cat saw the mouse",
      "the mouse ran away from the house",
      "the cat finally ate the mouse",
      "the end of the mouse story"
     ]

In [104]:
#instantiate CountVectorizer()
cv=CountVectorizer(stop_words=(["ate", "cat","from","had"]))
 
# this steps generates word counts for the words in your docs
word_count_vector=cv.fit_transform(docs)
print(word_count_vector.shape)
#(5, 16)
#We should have 5 rows (5 docs) and 16 columns (16 unique words, minus single character words):

tokens = cv.get_feature_names()
print(tokens)
# ['ate', 'away', 'cat', 'end', 'finally', 'from', 'had', 'house', 'little', 'mouse', 'of', 'ran', 'saw', 'story', 'the', 'tiny']


print(len(tokens))
#16

#there is 5 documents and 16 unique words

#it returns term-document matrix.
print(word_count_vector.toarray())
# [[0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 1]
#  [0 0 1 0 0 0 0 0 0 1 0 0 1 0 2 0]
#  [0 1 0 0 0 1 0 1 0 1 0 1 0 0 2 0]
#  [1 0 1 0 1 0 0 0 0 1 0 0 0 0 2 0]
#  [0 0 0 1 0 0 0 0 0 1 1 0 0 1 2 0]]

# create an index for each row
doc_names = ['Doc{:d}'.format(idx) for idx, _ in enumerate(word_count_vector)]
df = pd.DataFrame(data=word_count_vector.toarray(), index=doc_names,
                  columns=tokens)
df

(5, 12)
['away', 'end', 'finally', 'house', 'little', 'mouse', 'of', 'ran', 'saw', 'story', 'the', 'tiny']
12
[[0 0 0 1 1 1 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0 1 0 2 0]
 [1 0 0 1 0 1 0 1 0 0 2 0]
 [0 0 1 0 0 1 0 0 0 0 2 0]
 [0 1 0 0 0 1 1 0 0 1 2 0]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


away  end  finally  house  little  mouse  of  ran  saw  story  the  tiny
Doc0     0    0        0      1       1      1   0    0    0      0    1     1
Doc1     0    0        0      0       0      1   0    0    1      0    2     0
Doc2     1    0        0      1       0      1   0    1    0      0    2     0
Doc3     0    0        1      0       0      1   0    0    0      0    2     0
Doc4     0    1        0      0       0      1   1    0    0      1    2     0

In [105]:
tfidf_transformer=TfidfTransformer(smooth_idf=True,use_idf=True)
tfidf_transformer.fit(word_count_vector)

#TfidfTransformer(norm='l2', smooth_idf=True, sublinear_tf=False, use_idf=True)

# print idf values
df_idf = pd.DataFrame(tfidf_transformer.idf_, index=tokens,columns=["idf_weights"])

df_idf

idf_weights
away        2.098612
end         2.098612
finally     2.098612
house       1.693147
little      2.098612
mouse       1.000000
of          2.098612
ran         2.098612
saw         2.098612
story       2.098612
the         1.000000
tiny        2.098612

In [106]:
# count matrix
count_vector=cv.transform(docs)
 
# tf-idf scores
tf_idf_vector=tfidf_transformer.transform(count_vector)

In [100]:
#get tfidf vector for first document
first_document_vector=tf_idf_vector[0]
 
#print the scores
df = pd.DataFrame(first_document_vector.T.todense(), index=tokens, columns=["tf-idf"])
df.sort_values(by=["tf-idf"],ascending=False)

tf-idf
tf_idf     1.0